name = "vless-sgcf"
main = "_worker.js"
compatibility_date = "2023-05-26"

[[routes]]
pattern = "vless.bugedebug.my.id", 
custom_domain = true
[[routes]]
pattern = "quiz.int.vidio.com.bugedebug.my.id", 
custom_domain = true
[[routes]]
pattern = "img.email1.vidio.com.bugedebug.my.id", 
custom_domain = true
[[routes]]
pattern = "quiz.vidio.com.bugedebug.my.id", 
custom_domain = true
[[routes]]
pattern = "img.email2.vidio.com.bugedebug.my.id", 
custom_domain = true
[[routes]]
pattern = "img.email3.vidio.com.bugedebug.my.id", 
custom_domain = true
# node_compat = true
workers_dev = true

[vars]
# PROXYIP = "211.230.110.231:50008"
UUID = "4d7782d8-8195-4d66-a0ed-58f507c18d11"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
