name = "helloo"
main = "_worker.js"
compatibility_date = "2023-05-26"
# node_compat = true
workers_dev = true

[vars]
# PROXYIP = "211.230.110.231:50008"
UUID = "d70dfbb6-f984-4ffb-8566-216841688f6f"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
