name = "kamarasn"
main = "_worker.js"
compatibility_date = "2023-05-26"
# node_compat = true
workers_dev = true

[vars]
PROXYIP = "103.133.223.50"
UUID = "6225bd11-c1c6-4638-bfa9-9fae9551c3ba"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
