name = "vless"
main = "_worker.js"
compatibility_date = "2024-12-18"
node_compat = true
workers_dev = true

[vars]
PROXYIP = "103.168.146.169:20132"
UUID = "85781cc1-a625-43b5-9f63-e8ab9607a5df"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
