name = "server-sg"
main = "_worker.js"
compatibility_date = "2023-05-26"
[[routes]] =
pattern = "sg1.sempak-host.my.id"
custom_domain = true
[[routes]] =
pattern = "quiz.int.vidio.com.sg1.sempak-host.my.id"
custom_domain = true
[[routes]] =
pattern = "quiz.vidio.com.sg1.sempak-host.my.id"
custom_domain = true

[vars]
# PROXYIP = "211.230.110.231:50008"
UUID = "00649168-0b8e-4ef1-85b3-504a9497f525"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
