name = "bansos"
main = "_worker.js"
# node_compat = true
workers_dev = true

[vars]
PROXYIP = "103.168.146.169:20132"
UUID = "290bbb4a-accb-457d-a4b3-3fc9e6580b6d"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
