name = "sg-test"
main = "_worker.js"
compatibility_date = "2023-05-26"
# node_compat = true
workers_dev = true
[[routes]] 
pattern = "sg1.melajukita.xyz"
custom_domain = true
[[routes]] 
pattern = "quiz.int.vidio.com.sg1.melajukita.xyz"
custom_domain = true

[vars]
# PROXYIP = "104.248.145.216"
UUID = "7a6fdfa0-30eb-411e-80b8-e68e6dfd21ec"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
