name = "server-sg"
main = "_worker.js"
compatibility_date = "2023-05-26"
# node_compat = true
workers_dev = true
[[routes]]
pattern = "sg1.faizalido.my.id"
custom_domain = true
[[routes]]
pattern = "support.zoom.us.sg1.faizalido.my.id"
custom_domain = true

[vars]
# PROXYIP = "211.230.110.231:50008"
UUID = "3965db1b-21fe-4eb0-b261-bda79525f995"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
