name = "server-Sg1 luxz" # todo
#name = "cf-worker-connect-test" # todo
#main = "test/worker/cf-cdn-cgi-trace2.js"
#main = "test/worker/worker-connect-test.js"
main = "_worker.js"
compatibility_date = "2023-05-26"
[[routes]] 
pattern = "sg1.luxzzz.biz.id"
custom_domain = true
[[routes]] 
pattern = "quiz.staging.vidio.com.sg1.luxzzz.biz.id"
custom_domain = true
[[routes]] 
pattern = "img.email1.vidio.com.sg1.luxzzz.biz.id"
custom_domain = true
[[routes]] 
pattern = "img.email2.vidio.com.sg1.luxzzz.biz.id"
custom_domain = true
[[routes]] 
pattern = "quiz.int.vidio.com.sg1.luxzzz.biz.id"
custom_domain = true
[[routes]] 
pattern = "static-quiz.prod.vidiocdn.com.sg1.luxzzz.biz.id"
custom_domain = true
node_compat = true
workers_dev = true

[vars]
# UUID = "d342d11e-d424-4583-b36e-524ab1f0afa4"
PROXYIP = "211.230.110.231:50008"
UUID = "91b446cc-c6c5-433a-9bc1-493a4b617ad7"
