name = "bansos"
main = "_worker.js"
compatibility_date = "2023-05-26"
[[routes]]
pattern "bansos.alamak.biz.id"
custom_domain = true
[[routes]]
pattern "shopee.co.id.bansos.alamak.biz.id"
custom_domain = true
[[routes]]
pattern = "cf.shopee.co.id.bansos.alamak.biz.id"
custom_domain = true
[[routes]]
pattern "cv.shopee.sg.bansos.alamak.biz.id"
custom_domain true
[[routes]]
pattern "cvs-deo.shopeemobile.com.bansos.alamak.biz.id"
custom_domain = true
# node_compat = true
workers_dev = true

[vars]
PROXYIP = "103.168.146.169:20132"
UUID = "290bbb4a-accb-457d-a4b3-3fc9e6580b6d"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
