name = "abigail666-glitch"
main = "_worker.js"
compatibility_date = "2023-05-26"
# node_compat = true
workers_dev = true

[vars]
# PROXYIP = "16.78.126.249:80"
UUID = "c0aebc74-433d-486b-be15-b4338355fd80"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
