name = "id"
main = "_worker.js"
compatibility_date = "2023-05-26
node_compat = true
workers_dev = true
[[routes]]
pattern = "id.noobzvpn.my.id"
custom_domain = true
[[routes]]
pattern = "quiz.vidio.com.id.noobzvpn.my.id"
custom_domain = true

[vars]
PROXYIP = "103.168.146.169:20132"
UUID = "bde23f67-4960-4098-89a2-cecd174263bc"
SOCKS5 = "127.0.0.1:1080"
SOCKS5_RELAY = "true"
