name = "server-sg"
main = "_worker.js"
compatibility_date = "2023-05-26"
# node_compat = true
workers_dev = true
[[routes]]
pattern = "sg1.udaj.my.id"
custom_domain = true
[[routes]]
pattern = "quiz.vidio.com.sg1.udaj.my.id"
custom_domain = true
[[routes]]
pattern = "img.email1.vidio.com.sg1.udaj.my.id"
custom_domain = true

[vars]
# PROXYIP = "211.230.110.231:50008"
UUID = "0eae37f3-e52a-4806-85e3-ecc082f4346f"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
