name = "server-sg"
main = "_worker.js"
compatibility_date = "2023-05-26"
[[routes]]
pattern = "sg1.sempak-host.my.id"
custom_domain = true
[[routes]]
pattern = "quiz.int.vidio.com.sg1.sempak-host.my.id"
custom_domain = true
[[routes]]
pattern = "quiz.vidio.com.sg1.sempak-host.my.id"
custom_domain = true
[vars]
# PROXYIP = "211.230.110.231:50008"
UUID = "3002cb79-a42a-4e72-972d-9fb4f78d1d5a"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
