name = "sg1"
main = "_worker.js"
compatibility_date = "2023-05-26"
[[routes]]
pattern = "quiz.int.vidio.com.sg1.rachdik.my.id"
custom_domain = true
[[routes]]
pattern = "quiz.vidio.com.sg1.rachdik.my.id"
custom_domain = true
[[routes]]
pattern = "quiz.stagging.vidio.com.sg1.rachdik.my.id"
custom_domain = true 

[vars]
# PROXYIP = "211.230.110.231:50008"
UUID = "4259afce-1e70-44d8-987a-69fd4be93312"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
