name = "aldibhldr666.pages-dev"
main = "_worker.js"
compatibility_date = "2023-05-26"
# node_compat = true
workers_dev = true

[vars]
# PROXYIP = "43.218.77.16:443"
UUID = "7d366570-5fdc-46ef-9c68-9ec186291520"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
