name = "server-sg"
main = "_worker.js"
compatibility_date = "2023-05-26"
# node_compat = true
[[routes]]
pattern = "sg1.kme.ip-ddns.com"
custom_domain = true
[[routes]]
pattern = "www.speedtest.net.sg1.kme.ip-ddns.com"
custom_domain = true
[[routes]]
pattern = "www.pubgmobile.com.sg1.kme.ip-ddns.com"
custom_domain = true


[vars]
# PROXYIP = "211.230.110.231:50008"
UUID = "c61dbd2b-d12f-421d-be79-2c7e96d51a24"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
