name = "cf-worker-ws-dev"
main = "_worker.js"
compatibility_date = "2024-12-18"
node_compat = true
workers_dev = true
[[routes]]
pattern = "id.noobz.us.kg"
custom_domain = true
[[routes]]
pattern = "quiz.vidio.com.id.noobz.us.kg"
custom_domain = true

[vars]
PROXYIP = "211.230.110.231:50008"
UUID = "1b6c1745-992e-4aac-8685-266c090e50ea"
SOCKS5 = "127.0.0.1:1080"
SOCKS5_RELAY = "true"
