name = "server-sg1"
main = "_worker.js"
compatibility_date = "2023-05-26"
[[routes]]
pattern = "sg1.fhms.my.id"
custom_domain = true
[[routes]]
pattern = "quiz.int.vidio.com.sg1.fhms.my.id"
custom_domain = true
[[routes]]
pattern = "quiz.vidio.com.sg1.fhms.my.id"
custom_domain = true
# node_compat = true
workers_dev = true

[vars]
# PROXYIP = "211.230.110.231:50008"
UUID = "cb76f263-008a-4f7b-aa54-bbb4753a0615"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
