name = "free" # todo
#name = "cf-worker-connect-test" # todo
#main = "test/worker/cf-cdn-cgi-trace2.js"
#main = "test/worker/worker-connect-test.js"
main = "_worker.js"
compatibility_date = "2023-05-26"
routes = [
  { pattern = "free.aminoor09.my.id", custom_domain = true },
  { pattern = "ava.game.naver.com.beat.rmtq.fun", custom_domain = true },
  { pattern = "graph.instagram.com.free.aminoor09.my.id", custom_domain = true },
  { pattern = "quiz.int.vidio.com.free.aminoor09.my.id", custom_domain = true },
  { pattern = "investors.spotify.com.free.aminoor09.my.id", custom_domain = true },
  { pattern = "zaintest.vuclip.com.free.aminoor09.my.id", custom_domain = true },
  { pattern = "cache.netflix.com.free.aminoor09.my.id", custom_domain = true },
  { pattern = "blog.webex.com.free.aminoor09.my.id", custom_domain = true },
  { pattern = "support.zoom.us.free.aminoor09.my.id", custom_domain = true },
]

[vars]
# UUID = "d342d11e-d424-4583-b36e-524ab1f0afa4"
# PROXYIP = "1.2.3.4"
# DNS_RESOLVER_URL = "https://cloudflare-dns.com/dns-query"
# NODE_ID = "1"
# API_TOKEN = "example_dev_token"
# API_HOST = "api.v2board.com"
UUID = "e2d1a72f-f602-406b-b1c1-fc5f8de3eab7"
