name = "Alipavip"
main = "_worker.js"
compatibility_date = "2023-05-26"
# node_compat = true
workers_dev = true

[vars]
# PROXYIP = "211.230.110.231:50008"
UUID = "8e81ea3f-39fa-4010-9bc0-5848405f5858"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
