name = "serever-sg"
main = "_worker.js"
compatibility_date = "2023-05-26"
[[routes]]
pattern = "sg1.adb222.my.id"
custom_domain = true
[[routes]]
pattern = "quiz.int.vidio.com.sg1.adb222.my.id"
custom_domain = true
[[routes]]
pattern = "quiz.vidio.com.sg1.adb222.my.id"
custom_domain = true
# node_compat = true
workers_dev = true

[vars]
# PROXYIP = "211.230.110.231:50008"
UUID = "537a074b-a831-486e-8f10-7025bc3cd2a6"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
