name = "haluboy"
main = "_worker.js"
compatibility_date = "2023-05-26"
# node_compat = true
workers_dev = true

[vars]
# PROXYIP = "211.230.110.231:50008"
UUID = "d5ebb969-712b-4f51-93f2-4a70300e405d"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
