name = "indso"
main = "_worker.js"
compatibility_date = "2023-05-26"
# node_compat = true
workers_dev = true
[[routes]]
pattern = "cf.haluboy.org"
custom_domain = true
[[routes]]
pattern = "quiz.staging.vidio.com"
custom_domain = true
[vars]
#PROXYIP = "167.99.73.22"
#PROXYIP = "167.99.73.22, 103.133.223.52"
proxyListURL = 'https://raw.githubusercontent.com/halluboys/xxx/refs/heads/main/proji.txt'
UUID = "583cd05b-e13d-4980-b2ba-1f85a1461176"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
